const ADD_DISH = 'ADD_DISH';
const GET_ALL_DISHES = 'GET_ALL_DISHES';
const DELETE_DISH = 'DELETE_DISH';
const GET_RESTAURANT_PROFILE = 'GET_RESTAURANT_PROFILE';
const GET_ORDERS = 'GET_ORDERS';

export { ADD_DISH, GET_ALL_DISHES, DELETE_DISH, GET_RESTAURANT_PROFILE, GET_ORDERS }